// GENERATED by runs/material-variants/the-demo-mvp-four-materials-on-webgpu-live-on-the-demo-page/web/sync_to_dashboard.py
// SOURCE OF TRUTH: that run's web/demo4.css -- edit there, then re-run the sync.
export default `
/* demo4.css -- the shell around mpm4-webgpu.js. No external fonts, no CDNs, no network.
   Aesthetic per spec/aesthetic.md at full strength: Frutiger-era gloss and aquatic light, delivered
   at 2026 framerates, wrapped around chrome that is solid, legible and obviously mechanical. */

.mpm4 { position:absolute; inset:0; display:flex; flex-direction:column; overflow:hidden;
  background:#05070b; color:#cfe6ef; isolation:isolate;
  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; -webkit-user-select:none; user-select:none; }

/* ------------------------------------------------------------------ stage */
.mpm4 .stage { position:relative; flex:1 1 auto; min-height:0; display:grid; place-items:center;
  background:radial-gradient(120% 90% at 50% 8%, #0b1622 0%, #05070b 62%); }
.mpm4 .frame { position:relative; aspect-ratio:1/1; height:100%; max-width:100%; max-height:100%;
  border:1px solid #14303c; border-radius:4px; overflow:hidden;
  box-shadow:0 0 0 1px rgba(0,0,0,.6), 0 18px 60px rgba(0,0,0,.65), inset 0 0 60px rgba(0,0,0,.55); }
.mpm4 canvas { position:absolute; inset:0; width:100%; height:100%; display:block; touch-action:none; cursor:crosshair; }
/* aqueous sheen: the one unapologetically Frutiger element, composited on the GPU */
.mpm4 .sheen { position:absolute; inset:-25%; pointer-events:none; mix-blend-mode:screen; opacity:.42;
  background:
    radial-gradient(38% 30% at 22% 16%, rgba(60,220,255,.30), transparent 70%),
    radial-gradient(34% 26% at 82% 78%, rgba(150,60,255,.22), transparent 70%),
    radial-gradient(52% 40% at 50% 112%, rgba(20,255,180,.13), transparent 70%);
  animation:mpm4-drift 26s ease-in-out infinite alternate; }
@keyframes mpm4-drift { from{transform:translate3d(-2%,-1%,0) scale(1)} to{transform:translate3d(2%,1.5%,0) scale(1.07)} }
.mpm4 .scan { position:absolute; inset:0; pointer-events:none; opacity:.13;
  background:repeating-linear-gradient(180deg,rgba(255,255,255,.10) 0 1px,transparent 1px 3px); }
.mpm4 .vig { position:absolute; inset:0; pointer-events:none;
  background:radial-gradient(78% 70% at 50% 44%,transparent 42%,rgba(0,0,0,.72) 100%); }
.mpm4 .bounds { position:absolute; pointer-events:none;
  left:2.344%; right:2.344%; top:2.344%; bottom:2.344%;
  border:1px solid rgba(111,211,238,.22); border-top-color:rgba(111,211,238,.10);
  box-shadow:0 0 0 100vmax rgba(4,10,16,.34); }
.mpm4 .glass { position:absolute; inset:0; pointer-events:none;
  background:linear-gradient(180deg,rgba(255,255,255,.055) 0%,rgba(255,255,255,0) 42%); }

/* ------------------------------------------------------------------ heads-up readout */
.mpm4 .hud { position:absolute; left:10px; bottom:9px; right:10px; pointer-events:none;
  display:flex; gap:7px; flex-wrap:wrap; align-items:flex-end; }
.mpm4 .chip { font-size:10px; letter-spacing:.12em; color:#4d7686; background:rgba(6,13,19,.72);
  border:1px solid #142a35; border-radius:3px; padding:3px 7px; backdrop-filter:blur(3px); }
.mpm4 .chip b { color:#7fd8f0; font-weight:600; letter-spacing:.06em; }
.mpm4 .chip.warn b { color:#ffd24d; }
.mpm4 .chip.bad b { color:#ff8f8f; }
.mpm4 .hint { position:absolute; left:10px; top:9px; font-size:10px; letter-spacing:.15em;
  color:#3f6474; pointer-events:none; text-transform:uppercase; }
.mpm4 .title { position:absolute; right:11px; top:8px; text-align:right; pointer-events:none; }
.mpm4 .title h1 { margin:0; font-size:12px; letter-spacing:.30em; font-weight:700; color:#8fd4e8;
  text-shadow:0 0 18px rgba(70,220,255,.35); }
.mpm4 .title p { margin:2px 0 0; font-size:9.5px; letter-spacing:.13em; color:#3f6474; }

/* ------------------------------------------------------------------ controls: solid, mechanical */
.mpm4 .ctl { flex:0 0 auto; display:flex; flex-wrap:wrap; gap:12px; align-items:flex-start;
  padding:10px 12px 12px; background:linear-gradient(180deg,#0a1119,#070c12);
  border-top:1px solid #13232e; box-shadow:0 -14px 34px rgba(0,0,0,.55); }
.mpm4 .grp { display:flex; flex-direction:column; gap:5px; }
.mpm4 .lbl { font-size:9px; letter-spacing:.22em; color:#3f6474; text-transform:uppercase; }
.mpm4 .row { display:flex; gap:5px; align-items:center; flex-wrap:wrap; }
.mpm4 button { font:inherit; font-size:10.5px; letter-spacing:.10em; color:#9fc4d2; cursor:pointer;
  background:linear-gradient(180deg,#16222d,#0d151d); border:1px solid #1d3441; border-radius:3px;
  padding:7px 10px; text-transform:uppercase; position:relative;
  box-shadow:inset 0 1px 0 rgba(255,255,255,.07), 0 1px 0 rgba(0,0,0,.6);
  transition:background .10s, color .10s, border-color .10s, transform .04s; }
.mpm4 button:hover { color:#dff2fa; border-color:#2b5567; background:linear-gradient(180deg,#1b2b38,#101a24); }
.mpm4 button:active { transform:translateY(1px); }
.mpm4 button.on { color:#04121a; border-color:#7fd8f0;
  background:linear-gradient(180deg,#a9e9fb,#5cc0dd); box-shadow:0 0 14px rgba(110,215,240,.35); }
.mpm4 button .sw { display:inline-block; width:8px; height:8px; border-radius:2px; margin-right:6px;
  vertical-align:baseline; box-shadow:0 0 7px currentColor; }
.mpm4 button.mat.on { color:#04121a; }
.mpm4 input[type=range] { width:130px; accent-color:#6fd3ee; }
.mpm4 .val { font-size:10.5px; color:#7fd8f0; min-width:44px; }
.mpm4 .note { font-size:9.5px; line-height:1.5; color:#3f6474; max-width:28ch; }
.mpm4 .note b { color:#6f9fb2; font-weight:600; }
.mpm4 .badge { margin-left:auto; align-self:flex-end; font-size:9px; letter-spacing:.16em; color:#2f4c5b;
  border:1px solid #12242e; padding:4px 8px; border-radius:3px; background:rgba(8,16,22,.6); }

/* ------------------------------------------------------------------ the no-WebGPU path */
.mpm4 .fallback { position:absolute; inset:0; display:grid; place-items:center; text-align:center;
  padding:26px; background:rgba(5,7,11,.92); z-index:5; }
/* An author display:grid beats the UA stylesheet's [hidden]{display:none}. WITHOUT this rule the
   "no WebGPU" overlay renders on top of a perfectly working simulation and dims the entire page --
   which is exactly what it did until a full-page capture showed it. */
.mpm4 .fallback[hidden] { display:none; }
.mpm4 .fallback div { max-width:46ch; }
.mpm4 .fallback h2 { margin:0 0 12px; font-size:15px; letter-spacing:.16em; color:#8fd4e8; }
.mpm4 .fallback p { margin:0 0 8px; font-size:12px; line-height:1.7; color:#7f9fae; }
.mpm4 .fallback code { color:#cfe6ef; }

@media (prefers-reduced-motion: reduce) { .mpm4 .sheen { animation:none } }
@media (max-width: 720px) {
  .mpm4 .ctl { gap:9px; padding:8px 9px 10px; }
  .mpm4 button { padding:8px 8px; font-size:10px; }
  .mpm4 .note { display:none; }
  .mpm4 input[type=range] { width:104px; }
}
`;
