"""Emit web/params.js for the LEARNED-GRID-UPDATE port, straight from sim.physics (fluid).

Canonical-physics rule: a port may reimplement the step, never the parameters. Nothing here is typed
by hand; every constant is read out of `sim.physics` and stamped with the version hash.

Also emits web/nnweights.js: the trained MLP weights, flattened into the exact layout the WGSL shader
indexes, base64-encoded so the standalone task page stays self-contained (no fetch, no CDN).

    .venv/Scripts/python.exe .../web/gen_params.py
"""
import base64
import json
import pathlib
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT))

import sim.physics as phys                       # noqa: E402
from sim.physics import core as C                # noqa: E402

RUN = pathlib.Path(__file__).resolve().parents[1]
WEB = RUN / "web"
TRAIN = RUN / "train"
F = phys.MAT["fluid"]
WIDTHS = (8, 16, 32, 64)
N_IN = 8

params = {
    "dim": C.dim, "n_grid": C.n_grid, "dx": C.dx, "inv_dx": C.inv_dx,
    "gravity": C.gravity, "bound": C.bound, "floor_y": C.floor_y,
    "E": F["E"], "dt": F["dt"], "rho": F["rho"], "nu": F["nu"], "fric": F["fric"],
    "color": F["color"],
    # Fixed-point atomic scales, in units of one particle mass. kM is two bits looser than the
    # elastic port's 24 because the canonical water scenes reach ~430 particle masses on the
    # heaviest node and 2^(32-24) = 256 would saturate; 2^(32-22) = 1024 clears it.
    "kM": 22, "kV": 20,
    "substeps_per_frame": int(round((1.0 / 60.0) / F["dt"])),
    "physics_version": phys.VERSION,
    "source": "sim.physics (MAT['fluid'] + sim.physics.core world constants)",
}


def flatten(z, h, tag):
    """[W1 (N_IN*h) | b1 (h) | W2 (h*h) | b2 (h) | W3 (h*2) | b3 (2)], all row-major."""
    parts = [z[f"{h}_W1"].reshape(-1), z[f"{h}_b1"], z[f"{h}_W2"].reshape(-1), z[f"{h}_b2"],
             z[f"{h}_W3"].reshape(-1), z[f"{h}_b3"]]
    v = np.concatenate([p.astype(np.float32).ravel() for p in parts])
    want = N_IN * h + h + h * h + h + h * 2 + 2
    assert v.size == want, (tag, h, v.size, want)
    return v


def main():
    body = json.dumps(params, indent=2)
    (WEB / "params.js").write_text(
        "// GENERATED by web/gen_params.py from sim.physics -- do not edit.\n"
        f"// physics_version: {phys.VERSION}\nvar MPM_PARAMS = {body};\n"
        "if (typeof module === 'object' && module.exports) { module.exports = MPM_PARAMS; }\n",
        encoding="utf-8")

    nets = {}
    for tag, fn in (("point", "weights.npz"), ("deriv", "weights_grid.npz")):
        z = np.load(TRAIN / fn)
        for h in WIDTHS:
            v = flatten(z, h, tag)
            nets[f"{tag}{h}"] = {
                "tag": tag, "hidden": h, "n_in": N_IN, "count": int(v.size),
                "b64": base64.b64encode(v.tobytes()).decode("ascii"),
            }
    meta = {"widths": list(WIDTHS), "n_in": N_IN,
            "inputs": ["m_hat", "p_hat_x", "p_hat_y", "wallL", "wallR", "wallB", "wallT", "friction"],
            "variants": {"point": "stage 1: cell-wise mass-weighted MSE",
                         "deriv": "stage 2: + first-difference (derivative) loss on occupied cells"},
            "nets": nets}
    (WEB / "nnweights.js").write_text(
        "// GENERATED by web/gen_params.py -- trained MLP weights, float32 little-endian, base64.\n"
        f"var MPM_NN = {json.dumps(meta)};\n"
        "if (typeof module === 'object' && module.exports) { module.exports = MPM_NN; }\n",
        encoding="utf-8")
    print("wrote params.js + nnweights.js; physics_version", phys.VERSION)
    for h in WIDTHS:
        print(f"  h={h:3d}  {nets['point' + str(h)]['count']} floats")


if __name__ == "__main__":
    main()
