// GENERATED by web/gen_params.py from sim.physics -- do not edit.
// physics_version: phys-c518316a4a05
var MPM_PARAMS = {
  "dim": 2,
  "n_grid": 128,
  "dx": 0.0078125,
  "inv_dx": 128.0,
  "gravity": 9.8,
  "bound": 3,
  "floor_y": 0.0234375,
  "E": 900.0,
  "dt": 5e-05,
  "rho": 1.0,
  "nu": 0.2,
  "fric": 0.0,
  "color": "#4db6ff",
  "kM": 22,
  "kV": 20,
  "substeps_per_frame": 333,
  "physics_version": "phys-c518316a4a05",
  "source": "sim.physics (MAT['fluid'] + sim.physics.core world constants)"
};
if (typeof module === 'object' && module.exports) { module.exports = MPM_PARAMS; }
