"""Copy the portable demo bundle into the dashboard as ES modules.

`web/` is the SINGLE SOURCE OF TRUTH. The dashboard gets a generated copy so there is exactly one
place to edit and no chance of the Demo tab and the transplantable page drifting apart.

The transformation is deliberately trivial -- verbatim copy plus one export line -- rather than a
rewrite of the module wrapper, because a transformation with any cleverness in it is a place for the
two copies to differ. The files already attach themselves to `self`, so the ES-module wrapper only
has to re-export what they attached.

    .venv/Scripts/python.exe runs/.../web/sync_to_dashboard.py
"""
import pathlib

WEB = pathlib.Path(__file__).resolve().parent
DST = WEB.parents[3] / "harness" / "dashboard" / "src" / "components" / "mpm"

BANNER = ("// GENERATED by runs/material-variants/"
          "incorporate-improved-materials-on-real-demo-page-and-improve-polish/web/sync_to_dashboard.py\n"
          "// SOURCE OF TRUTH: that run's web/%s -- edit there, then re-run the sync.\n")

GLOBAL = "(typeof self !== 'undefined' ? self : globalThis)"


def main():
    DST.mkdir(parents=True, exist_ok=True)

    params = (WEB / "params.js").read_text(encoding="utf-8")
    (DST / "params.js").write_text(
        BANNER % "params.js" + params + "\nexport default MPM_PARAMS;\n", encoding="utf-8")

    engine = (WEB / "mpm4-webgpu.js").read_text(encoding="utf-8")
    assert "require(" not in engine, "the engine must not reference require() -- bundlers choke"
    (DST / "mpm4.js").write_text(
        BANNER % "mpm4-webgpu.js" + "import './params.js';\n\n" + engine +
        "\nexport default %s.MPM4;\n" % GLOBAL, encoding="utf-8")

    ui = (WEB / "demo4.js").read_text(encoding="utf-8")
    (DST / "demo4.js").write_text(
        BANNER % "demo4.js" + "import './mpm4.js';\n\n" + ui +
        "\nexport default %s.MPMDemo4;\n" % GLOBAL, encoding="utf-8")

    css = (WEB / "demo4.css").read_text(encoding="utf-8")
    assert "`" not in css and "${" not in css, "CSS would break the template literal"
    (DST / "demo4.css.js").write_text(
        BANNER % "demo4.css" + "export default `\n" + css + "`;\n", encoding="utf-8")

    for f in sorted(DST.glob("*.js")):
        print("wrote", f, f.stat().st_size, "bytes")


if __name__ == "__main__":
    main()
