"""Emit web/params.js and web/netshape.js DIRECTLY from sim.physics and train/netspec.py.

No physical constant and no network dimension is typed by hand anywhere in the JS or the WGSL. Two
things this fixes relative to the four-material demo's generator, which was written against an older
physics version:

  * PER-MATERIAL POISSON RATIO. `mu` and `la` are now derived from each material's own `nu`
    (MAT[...]["nu"]), not from the global fallback `core.NU`. Rubber runs nu = 0.45; deriving its
    Lame parameters from 0.2 would have made the WebGPU rubber a different material from canonical
    rubber, which is exactly the ground-truth drift the canonical-physics rule exists to stop.
  * PER-MATERIAL DENSITY AND FRICTION are emitted so the page can report them, even though this
    harness runs a single particle density (see the note in the manifest's limitations).

    .venv/Scripts/python.exe runs/.../web/gen_params.py
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[3]))
sys.path.insert(0, str(HERE.parent / "train"))

import sim.physics as phys                      # noqa: E402
from sim.physics import core as C               # noqa: E402
import netspec as NS                            # noqa: E402

mats = {}
for name, cfg in C.MAT.items():
    nu = cfg.get("nu", C.NU)
    mats[name] = {
        "id": C.MAT_ID[name], "E": cfg["E"], "dt": cfg["dt"], "xi": cfg["xi"],
        "tc": cfg["tc"], "ts": cfg["ts"], "phi": cfg["phi"],
        "alpha": C.dp_alpha(cfg["phi"]),
        "nu": nu, "rho": cfg.get("rho", C.p_rho), "fric": cfg.get("fric", C.FRICTION),
        "mu": cfg["E"] / (2.0 * (1.0 + nu)),
        "la": cfg["E"] * nu / ((1.0 + nu) * (1.0 - 2.0 * nu)),
        "color": cfg["color"],
    }

params = {
    "dim": C.dim, "n_grid": C.n_grid, "dx": C.dx, "inv_dx": C.inv_dx, "p_rho": C.p_rho,
    "gravity": C.gravity, "bound": C.bound, "floor_y": C.floor_y, "NU": C.NU,
    "FRICTION": C.FRICTION, "MAX_P": C.MAX_P,
    "materials": mats, "mat_order": ["fluid", "elastic", "snow", "sand"], "mat_id": C.MAT_ID,
    # fixed-point atomic scales, measured in the earlier WebGPU task and carried over unchanged
    "kM": 24, "kV": 22,
    "physics_version": phys.VERSION,
    "source": "sim.physics (MAT with per-material nu/rho/fric, MAT_ID, dp_alpha, world constants)",
}

net = {
    "z_dim": NS.Z_DIM, "n_feat": NS.N_FEAT, "n_in": NS.N_IN, "n_in_pad": NS.N_IN_PAD,
    "n_out": NS.N_OUT, "n_out_pad": NS.N_OUT_PAD,
    "feat_names": NS.FEAT_NAMES, "out_names": NS.OUT_NAMES,
    "z_codes": [[float(v) for v in row] for row in NS.Z_CODES],
    "z_sep": NS.Z_SEP, "z_jitter": NS.Z_JITTER,
}

(HERE / "params.js").write_text(
    "// GENERATED by web/gen_params.py from sim.physics -- do not edit by hand.\n"
    f"// physics_version: {phys.VERSION}\n"
    f"var MPM_PARAMS = {json.dumps(params, indent=2)};\n"
    "if (typeof module === 'object' && module.exports) { module.exports = MPM_PARAMS; }\n"
    "if (typeof window !== 'undefined') { window.MPM_PARAMS = MPM_PARAMS; }\n", encoding="utf-8")
(HERE / "netshape.js").write_text(
    "// GENERATED by web/gen_params.py from train/netspec.py -- do not edit by hand.\n"
    f"var NET_SHAPE = {json.dumps(net, indent=2)};\n"
    "if (typeof window !== 'undefined') { window.NET_SHAPE = NET_SHAPE; }\n", encoding="utf-8")
print("physics_version:", phys.VERSION)
print("z codes:\n", NS.Z_CODES, "\nseparation", NS.Z_SEP, "jitter", NS.Z_JITTER)
for k, v in mats.items():
    print(f"  {k:8s} E={v['E']:7.1f} nu={v['nu']:.2f} rho={v['rho']:.2f} mu={v['mu']:8.2f} "
          f"la={v['la']:9.2f} dt={v['dt']:.1e}")
