// GENERATED by web/gen_params.py from sim.physics -- do not edit by hand.
// physics_version: phys-c518316a4a05
var MPM_PARAMS = {
  "dim": 2,
  "n_grid": 128,
  "dx": 0.0078125,
  "inv_dx": 128.0,
  "p_rho": 1.0,
  "gravity": 9.8,
  "bound": 3,
  "floor_y": 0.0234375,
  "NU": 0.2,
  "FRICTION": 0.5,
  "MAX_P": 16384,
  "materials": {
    "fluid": {
      "id": 0,
      "E": 900.0,
      "dt": 5e-05,
      "xi": 0.0,
      "tc": 0.0,
      "ts": 0.0,
      "phi": 0.0,
      "alpha": 0.0,
      "nu": 0.2,
      "rho": 1.0,
      "fric": 0.0,
      "mu": 375.0,
      "la": 250.0,
      "color": "#4db6ff"
    },
    "elastic": {
      "id": 1,
      "E": 580.0,
      "dt": 5e-05,
      "xi": 0.0,
      "tc": 0.0,
      "ts": 0.0,
      "phi": 0.0,
      "alpha": 0.0,
      "nu": 0.45,
      "rho": 1.2,
      "fric": 0.5,
      "mu": 200.0,
      "la": 1800.0000000000005,
      "color": "#ff9d5c"
    },
    "snow": {
      "id": 2,
      "E": 45.0,
      "dt": 5e-05,
      "xi": 10.0,
      "tc": 0.025,
      "ts": 0.0075,
      "phi": 0.0,
      "alpha": 0.0,
      "nu": 0.2,
      "rho": 0.3,
      "fric": 0.5,
      "mu": 18.75,
      "la": 12.5,
      "color": "#e6ecff"
    },
    "sand": {
      "id": 3,
      "E": 480.0,
      "dt": 0.0001,
      "xi": 0.0,
      "tc": 0.0,
      "ts": 0.0,
      "phi": 50.0,
      "alpha": 0.5599687663604146,
      "nu": 0.2,
      "rho": 1.6,
      "fric": 0.5,
      "mu": 200.0,
      "la": 133.33333333333334,
      "color": "#ffd24d"
    }
  },
  "mat_order": [
    "fluid",
    "elastic",
    "snow",
    "sand"
  ],
  "mat_id": {
    "fluid": 0,
    "elastic": 1,
    "snow": 2,
    "sand": 3
  },
  "kM": 24,
  "kV": 22,
  "physics_version": "phys-c518316a4a05",
  "source": "sim.physics (MAT with per-material nu/rho/fric, MAT_ID, dp_alpha, world constants)"
};
if (typeof module === 'object' && module.exports) { module.exports = MPM_PARAMS; }
if (typeof window !== 'undefined') { window.MPM_PARAMS = MPM_PARAMS; }
